artifacts_root: artifacts

data_ingestion:
  root_dir: artifacts/data-ingestion
  source_URL: https://github.com/entbappy/Branching-tutorial/raw/master/summarizer-data.zip
  local_data_file: artifacts/data-ingestion/data.zip
  unzip_dir: artifacts/data-ingestion

data_validation:
  root_dir : artifacts/data-validation
  STATUS_FILE : artifacts/data-validation/status.txt
  ALL_REQUIRED_FILES: ["train","test","validation"]



